name: Build and Release

on:
  push:
    branches:
      - build

jobs:
  build_and_release:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetches all history for all branches and tags.
          # Required for the version bump commit to be pushed correctly.
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Cache Pub dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Get pub dependencies
        run: flutter pub get

      - name: Bump version
        id: bump_version
        uses: shogo82148/actions-flutter-version-up@v1
        with:
          spec-file: pubspec.yaml

      - name: Commit version bump
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pubspec.yaml
          git commit -m "ci: Bump version to ${{ steps.bump_version.outputs.new-version }} [skip ci]"
          git push
          
      - name: Build APK
        run: flutter build apk --release

      - name: Build Web
        run: flutter build web --release


      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          working-directory: ./ios

      - name: Run Fastlane
        run: |
          bundle exec fastlane match
          bundle exec fastlane build
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
        working-directory: ./ios

      - name: Archive Web build for release
        run: zip -r build-web.zip ./build/web

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,ios/Runner.ipa,build-web.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ steps.bump_version.outputs.new-version }}"
          name: "Release v${{ steps.bump_version.outputs.new-version }}"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
